#Requires AutoHotkey v2.0

This.AlwaysActiveHKs := Map(
"Ctrl", ControlHK,
"#+Insert", AddMarkerHK,
"#+Del", DeleteMarkers,
"#+PrintScreen", ExtractImage,
"#+F", FocusControl,
"#+G", GenerateMarkersFromOcrHK,
"#+Left", MoveMouseLeftHK,
"#+Right", MoveMouseRightHK,
"#+Up", MoveMouseUpHK,
"#+Down", MoveMouseDownHK,
"#+Enter", PerformMouseClickHK,
"#+O", PerformOcrHK,
"#+Q", QuitHK,
"#+R", RepeatSearchForImageHK,
"#+Z", ReportMousePositionHK,
"#+K", ReportPixelColorHK,
"#+U", RouteMouseToFocusedControl,
"#+I", SearchForImageHK,
"#+X", SetMouseXCoordinateHK,
"#+Y", SetMouseYCoordinateHK,
"#+F1", ShowAboutBoxHK,
"#+D", ToggleEditorHK,
"#+P", TogglePauseHK,
"#+AppsKey", ToolsMenuHK,
"#+F10", ToolsMenuHK,
"#+V", ViewClipboardContents,
"#+C", ViewControlInfo,
"#+L", ViewControlList,
"#+M", ViewMouseAndCaretInfo,
"#+W", ViewWindowInfo,
)

This.OnlyWhenEditorActiveHKs := Map(
"#+H", AddHotspotButtonHK,
"!AppsKey", AddMenuHK,
"!+F10", AddMenuHK,
"+^Tab", ControlShiftTabHK,
"^Tab", ControlTabHK,
"^C", CopyItemHK,
"^N", CreateProjectHK,
"^X", CutItemHK,
"Del", DeleteItemHK,
"F2", EditItemHK,
"Enter", EnterSpaceHK,
"Space", EnterSpaceHK,
"^E", GenerateCodeHK,
"^I", InportCodeHK,
"^AppsKey", ItemMenuHK,
"^+F10", ItemMenuHK,
"Left", LeftRightHK,
"Right", LeftRightHK,
"AppsKey", MainMenuHK,
"+F10", MainMenuHK,
"#+N", NudgeCoordinates,
"^O", OpenProjectHK,
"^V", PasteItemHK,
"^!S", SaveProjectAsHK,
"^S", SaveProjectHK,
"#+B", SetBottomCornerCoordinatesToMouseCursor,
"#+S", SetCoordinatesToMouseCursor,
"#+T", SetTopCornerCoordinatesToMouseCursor,
"+Tab", ShiftTabHK,
"Tab", TabHK,
"^Z", UndoHK,
"Up", UpDownHK,
"Down", UpDownHK,
)

This.HKsExemptFromPause := ["#+Q", "#+F1", "#+P"]
