#Requires AutoHotkey v2.0

Static AlwaysActiveHKs := Map(
"Ctrl", ControlHK,
"#+Insert", AddMarkerHK,
"#+Del", DeleteMarkers,
"#+PrintScreen", ExtractImage,
"#+F", FocusControl,
"#+G", GenerateMarkersFromOcrHK,
"#+Left", MoveMouseLeftHK,
"#+Right", MoveMouseRightHK,
"#+Up", MoveMouseUpHK,
"#+Down", MoveMouseDownHK,
"#+O", PerformOcrHK,
"#+Q", QuitHK,
"#+R", RepeatSearchForImageHK,
"#+Z", ReportMousePositionHK,
"#+B", ReportPixelColorHK,
"#+U", RouteMouseToFocusedControl,
"#+I", SearchForImageHK,
"#+X", SetMouseXCoordinateHK,
"#+Y", SetMouseYCoordinateHK,
"#+F1", ShowAboutBoxHK,
"#+D", ToggleEditorHK,
"#+P", TogglePauseHK,
"#+V", ViewClipboardContents,
"#+C", ViewControlInfo,
"#+L", ViewControlList,
"#+M", ViewMouseInfo,
"#+W", ViewWindowInfo,
)

Static OnlyWhenActiveHKs := Map(
"#+H", AddHotspotButtonHK,
"AppsKey", ContextMenuHK,
"+^Tab", ControlShiftTabHK,
"^Tab", ControlTabHK,
"^C", CopyItemHK,
"^N", CreateProjectHK,
"^X", CutItemHK,
"Del", DeleteItemHK,
"F2", EditItemHK,
"Enter", EnterSpaceHK,
"Space", EnterSpaceHK,
"#+E", GenerateCodeHK,
"Left", LeftRightHK,
"Right", LeftRightHK,
"#+N", NudgeCoordinates,
"^O", OpenProjectHK,
"^V", PasteItemHK,
"^!S", SaveProjectAsHK,
"^S", SaveProjectHK,
"#+S", SetCoordinatesToMouseCursor,
"+Tab", ShiftTabHK,
"Tab", TabHK,
"^Z", UndoHK,
"Up", UpDownHK,
"Down", UpDownHK,
)
