#Requires AutoHotkey v2.0

Static ToolsMenuList := Array(
{Name: "&Nudge coordinates…`tShift+Windows+N", Handler: NudgeCoordinates},
{Name: "&Focus control…`tShift+Windows+F", Handler: FocusControl},
{Name: "&Extract image…`tShift+Windows+Print screen", Handler: ExtractImage},
{Name: "Search for &image…`tShift+Windows+I", Handler: SearchForImageHandler},
{Name: "&Repeat search for last image…`tShift+Windows+R", Handler: RepeatSearchForImageHandler},
{Name: "Perform &OCR…`tShift+Windows+O", Handler: PerformOCRHandler},
{Name: "&Generate markers from OCR…`tShift+Windows+G", Handler: GenerateMarkersFromOCRHandler},
{Name: "View &window info…`tShift+Windows+W", Handler: ViewWindowInfo},
{Name: "View &control info…`tShift+Windows+C", Handler: ViewControlInfo},
{Name: "View control &list…`tShift+Windows+L", Handler: ViewControlList},
{Name: "View &mouse info…`tShift+Windows+M", Handler: ViewMouseInfo},
{Name: "&View clipboard contents…`tShift+Windows+V", Handler: ViewClipboardContents},
)

Static GeneralParams := Array(
{Label: "Variable Name", Param: "VarName", Expression: 2}
)

Static GenericAddList := ["Button", "ToggleButton", "GraphicalButton", "GraphicalToggleButton", "HotspotButton", "HotspotToggleButton", "OCRButton", "CustomButton", "CustomToggleButton", "Checkbox", "GraphicalCheckbox", "HotspotCheckbox", "CustomCheckbox", "ComboBox", "HotspotComboBox", "OCRComboBox", "CustomComboBox", "Edit", "HotspotEdit", "OCREdit", "CustomEdit", "StaticText", "OCRText", "TabControl", "AccessibilityOverlay", "PluginOverlay", "StandaloneOverlay", "Marker"]
Static TabControlAddList := ["Tab", "GraphicalTab", "HotspotTab", "OCRTab", "CustomTab"]

Static ItemDefinitions := Map(
"AccessibilityOverlay", {OptionalParams: [{Expression: 1, Name: "Label"}], DefaultValues: ["AccessibilityOverlay"]},
"Button", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["Button"]},
"Checkbox", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["Checkbox"]},
"ComboBox", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "ChangeFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["ComboBox"]},
"CustomButton", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomButton"]},
"CustomCheckbox", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "CheckStateFunction"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomCheckbox"]},
"CustomComboBox", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "ChangeFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomComboBox"]},
"CustomEdit", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomEdit"]},
"CustomTab", {RequiredParams: [{Expression: 1, Name: "Label"}, ], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomTab"]},
"CustomToggleButton", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "CheckStateFunction"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomToggleButton"]},
"Edit", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["Edit"]},
"GraphicalButton", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}, {Expression: 4, Name: "Images"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["GraphicalButton", 0, 0, 0, 0, []]},
"GraphicalCheckbox", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}, {Expression: 4, Name: "CheckedImages"}, {Expression: 4, Name: "UncheckedImages"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["GraphicalCheckbox", 0, 0, 0,0, [], []]},
"GraphicalTab", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}, {Expression: 4, Name: "Images"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["GraphicalTab", 0, 0, 0, 0, []]},
"GraphicalToggleButton", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}, {Expression: 4, Name: "OnImages"}], OptionalParams: [{Expression: 4, Name: "OffImages"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["GraphicalToggleButton", 0, 0, 0, 0, [], []]},
"HotspotButton", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotButton", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]},
"HotspotCheckbox", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}, {Expression: 4, Name: "CheckedColors"}, {Expression: 4, Name: "UncheckedColors"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotCheckbox", 0, 0, "", ""], MenuActions: ["Set coordinates to mouse cursor"]},
"HotspotComboBox", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "ChangeFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotComboBox", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]},
"HotspotEdit", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotEdit", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]},
"HotspotTab", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotTab", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]},
"HotspotToggleButton", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}, {Expression: 4, Name: "OnColors"}, {Expression: 4, Name: "OffColors"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotToggleButton", 0, 0, "", ""], MenuActions: ["Set coordinates to mouse cursor"]},
"Marker", {RequiredParams: [{Expression: 2, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 2, Name: "HotkeyLabel"}], DefaultValues: ["Marker", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]},
"OCRButton", {RequiredParams: [{Expression: 1, Name: "LabelPrefix"}, {Expression: 1, Name: "DefaultLabel"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["", "", "TesseractBest", 0, 0, 0, 0]},
"OCRComboBox", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 1, Name: "DefaultValue"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "ChangeFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["OCRComboBox", "", "TesseractBest", 0, 0, 0, 0]},
"OCREdit", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["", "TesseractBest", 0, 0, 0, 0]},
"OCRTab", {RequiredParams: [{Expression: 1, Name: "DefaultLabel"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["", "TesseractBest", 0, 0, 0, 0]},
"OCRText", {RequiredParams: [{Expression: 1, Name: "ValuePrefix"}, {Expression: 1, Name: "DefaultValue"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["", "", "TesseractBest", 0, 0, 0, 0]},
"PluginOverlay", {OptionalParams: [{Expression: 1, Name: "Label"}, {Expression: 1, Name: "PluginName"}, {Expression: 4, Name: "CompensationFunction"}], DefaultValues: ["PluginOverlay", "", CompensatePluginCoordinates]},
"StandaloneOverlay", {OptionalParams: [{Expression: 1, Name: "Label"}, {Expression: 1, Name: "StandaloneName"}], DefaultValues: ["StandaloneOverlay"]},
"StaticText", {OptionalParams: [{Expression: 1, Name: "Value"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["StaticText"]},
"Tab", {RequiredParams: [{Expression: 1, Name: "Label"}, ], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["Tab"]},
"TabControl", {RequiredParams: [{Expression: 1, Name: "Label"}], DefaultValues: ["TabControl"]},
"ToggleButton", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["ToggleButton"]},
)
