#Requires AutoHotkey v2.0

This.ToolsMenuList := Array(
{Name: "&Nudge coordinates…`tShift+Windows+N", Handler: NudgeCoordinates},
{Name: "&Focus control…`tShift+Windows+F", Handler: FocusControl},
{Name: "&Extract image…`tShift+Windows+Print screen", Handler: ExtractImage},
{Name: "Search for &image…`tShift+Windows+I", Handler: SearchForImageHandler},
{Name: "&Repeat search for last image…`tShift+Windows+R", Handler: RepeatSearchForImageHandler},
{Name: "Perform &OCR…`tShift+Windows+O", Handler: PerformOCRHandler},
{Name: "&Generate markers from OCR…`tShift+Windows+G", Handler: GenerateMarkersFromOCRHandler},
{Name: "View &window info…`tShift+Windows+W", Handler: ViewWindowInfo},
{Name: "View &control info…`tShift+Windows+C", Handler: ViewControlInfo},
{Name: "View control &list…`tShift+Windows+L", Handler: ViewControlList},
{Name: "View &mouse and caret info…`tShift+Windows+M", Handler: ViewMouseAndCaretInfo},
{Name: "&View clipboard contents…`tShift+Windows+V", Handler: ViewClipboardContents},
)

This.GeneralParams := Array(
{Label: "Variable Name", Param: "VarName", Expression: 2}
)

This.GenericAddList := ["Button", "ToggleButton", "GraphicalButton", "GraphicalToggleButton", "HotspotButton", "HotspotToggleButton", "OCRButton", "CustomButton", "CustomToggleButton", "Checkbox", "GraphicalCheckbox", "HotspotCheckbox", "CustomCheckbox", "Edit", "HotspotEdit", "OCREdit", "CustomEdit", "ListBox", "HotspotListBox", "OCRListBox", "CustomListBox", "StaticText", "OCRText", "TabControl", "AccessibilityOverlay", "PluginOverlay", "StandaloneOverlay", "Marker"]
This.TabControlAddList := ["Tab", "GraphicalTab", "HotspotTab", "OCRTab", "CustomTab"]

This.ItemDefinitions := Map()
This.ItemDefinitions.Set("AccessibilityOverlay", {OptionalParams: [{Expression: 1, Name: "Label"}], DefaultValues: ["AccessibilityOverlay"]})
This.ItemDefinitions.Set("Button", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["Button"]})
This.ItemDefinitions.Set("Checkbox", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["Checkbox"]})
This.ItemDefinitions.Set("CustomButton", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomButton"]})
This.ItemDefinitions.Set("CustomCheckbox", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "CheckStateFunction"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomCheckbox"]})
This.ItemDefinitions.Set("CustomEdit", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomEdit"]})
This.ItemDefinitions.Set("CustomListBox", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "Options"}, {Expression: 4, Name: "ChangeFunctions"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomListBox"]})
This.ItemDefinitions.Set("CustomTab", {RequiredParams: [{Expression: 1, Name: "Label"}, ], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomTab"]})
This.ItemDefinitions.Set("CustomToggleButton", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "CheckStateFunction"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["CustomToggleButton"]})
This.ItemDefinitions.Set("Edit", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["Edit"]})
This.ItemDefinitions.Set("GraphicalButton", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}, {Expression: 4, Name: "Images"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["GraphicalButton", 0, 0, 0, 0, []], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("GraphicalCheckbox", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}, {Expression: 4, Name: "CheckedImages"}, {Expression: 4, Name: "UncheckedImages"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["GraphicalCheckbox", 0, 0, 0,0, [], []], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("GraphicalTab", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}, {Expression: 4, Name: "Images"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["GraphicalTab", 0, 0, 0, 0, []], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("GraphicalToggleButton", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}, {Expression: 4, Name: "OnImages"}], OptionalParams: [{Expression: 4, Name: "OffImages"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["GraphicalToggleButton", 0, 0, 0, 0, [], []], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("HotspotButton", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotButton", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]})
This.ItemDefinitions.Set("HotspotCheckbox", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}, {Expression: 4, Name: "CheckedColors"}, {Expression: 4, Name: "UncheckedColors"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotCheckbox", 0, 0, "", ""], MenuActions: ["Set coordinates to mouse cursor"]})
This.ItemDefinitions.Set("HotspotEdit", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotEdit", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]})
This.ItemDefinitions.Set("HotspotListBox", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 4, Name: "Options"}, {Expression: 4, Name: "ChangeFunctions"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotListBox", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]})
This.ItemDefinitions.Set("HotspotTab", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotTab", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]})
This.ItemDefinitions.Set("HotspotToggleButton", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}, {Expression: 4, Name: "OnColors"}, {Expression: 4, Name: "OffColors"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["HotspotToggleButton", 0, 0, "", ""], MenuActions: ["Set coordinates to mouse cursor"]})
This.ItemDefinitions.Set("ListBox", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "Options"}, {Expression: 4, Name: "ChangeFunctions"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["ListBox"]})
This.ItemDefinitions.Set("Marker", {RequiredParams: [{Expression: 2, Name: "Label"}, {Expression: 4, Name: "XCoordinate"}, {Expression: 4, Name: "YCoordinate"}], OptionalParams: [{Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 2, Name: "HotkeyLabel"}], DefaultValues: ["Marker", 0, 0], MenuActions: ["Set coordinates to mouse cursor"]})
This.ItemDefinitions.Set("OCRButton", {RequiredParams: [{Expression: 1, Name: "LabelPrefix"}, {Expression: 1, Name: "DefaultLabel"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["", "", "TesseractBest", 0, 0, 0, 0], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("OCREdit", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["", "TesseractBest", 0, 0, 0, 0], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("OCRListBox", {RequiredParams: [{Expression: 1, Name: "Label"}, {Expression: 1, Name: "DefaultValue"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "ChangeFunctions"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["OCRListBox", "", "TesseractBest", 0, 0, 0, 0], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("OCRTab", {RequiredParams: [{Expression: 1, Name: "DefaultLabel"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["", "TesseractBest", 0, 0, 0, 0], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("OCRText", {RequiredParams: [{Expression: 1, Name: "ValuePrefix"}, {Expression: 1, Name: "DefaultValue"}, {Expression: 1, Name: "OCRType"}, {Expression: 4, Name: "X1Coordinate"}, {Expression: 4, Name: "Y1Coordinate"}, {Expression: 4, Name: "X2Coordinate"}, {Expression: 4, Name: "Y2Coordinate"}], OptionalParams: [{Expression: 1, Name: "OCRLanguage"}, {Expression: 1, Name: "OCRScale"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["", "", "TesseractBest", 0, 0, 0, 0], MenuActions: ["Set top corner coordinates to mouse cursor", "Set bottom corner coordinates to mouse cursor"]})
This.ItemDefinitions.Set("PluginOverlay", {OptionalParams: [{Expression: 1, Name: "Label"}, {Expression: 1, Name: "PluginName"}, {Expression: 4, Name: "CompensationFunction"}], DefaultValues: ["PluginOverlay", "", CompensatePluginCoordinates]})
This.ItemDefinitions.Set("StandaloneOverlay", {OptionalParams: [{Expression: 1, Name: "Label"}, {Expression: 1, Name: "StandaloneName"}], DefaultValues: ["StandaloneOverlay"]})
This.ItemDefinitions.Set("StaticText", {OptionalParams: [{Expression: 1, Name: "Value"}, {Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["StaticText"]})
This.ItemDefinitions.Set("Tab", {RequiredParams: [{Expression: 1, Name: "Label"}, ], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["Tab"]})
This.ItemDefinitions.Set("TabControl", {RequiredParams: [{Expression: 1, Name: "Label"}], DefaultValues: ["TabControl"]})
This.ItemDefinitions.Set("ToggleButton", {RequiredParams: [{Expression: 1, Name: "Label"}], OptionalParams: [{Expression: 4, Name: "PreExecFocusFunctions"}, {Expression: 4, Name: "PostExecFocusFunctions"}, {Expression: 4, Name: "PreExecActivationFunctions"}, {Expression: 4, Name: "PostExecActivationFunctions"}, {Expression: 2, IsHotkey: 1, Name: "HotkeyCommand"}, {Expression: 1, Name: "HotkeyLabel"}, {Expression: 4, Name: "HotkeyFunctions"}], DefaultValues: ["ToggleButton"]})
