#Requires AutoHotkey v2.0

Plugin.DefaultOverlay := AccessibilityOverlay()
Plugin.DefaultOverlay.AddCustomControl("FocusDefaultOverlay")
Plugin.ChooserOverlay := AccessibilityOverlay()
Plugin.ChooserOverlay.AddCustomButton("Choose overlay", "", "ChoosePluginOverlay")

Standalone.DefaultOverlay := AccessibilityOverlay()
Standalone.DefaultOverlay.AddCustomControl("FocusDefaultOverlay")
Standalone.ChooserOverlay := AccessibilityOverlay()
Standalone.ChooserOverlay.AddCustomButton("Choose overlay", "", "ChooseStandaloneOverlay")

AreiaJaegerOverlay := AccessibilityOverlay("Areia/Jaeger")
AreiaJaegerOverlay.AddHotspotButton("Classic Mix", 678, 448)
AreiaJaegerOverlay.AddHotspotButton("Modern Mix", 775, 448)
Plugin.RegisterOverlay("Kontakt/Komplete Kontrol", AreiaJaegerOverlay)

EnginePluginOverlay := AccessibilityOverlay("Engine")
EnginePluginOverlay.AddHotspotButton("Load instrument", 320, 232)
EnginePluginQuickEditTab := HotspotTab("Quick edit", 574, 124)
EnginePluginProEditTab := HotspotTab("Pro edit", 628, 124)
EnginePluginBrowserTab := HotspotTab("Browser", 686, 124)
EnginePluginMixerTab := HotspotTab("Mixer", 744, 124)
EnginePluginPreferencesTab := HotspotTab("Preferences", 800, 124)
EnginePluginHelpTab := HotspotTab("Help", 850, 124)
EnginePluginOverlay.AddTabControl("", EnginePluginQuickEditTab, EnginePluginProEditTab, EnginePluginBrowserTab, EnginePluginMixerTab, EnginePluginPreferencesTab, EnginePluginHelpTab)
EnginePluginEngineTab := HotspotTab("Engine", 576, 168)
EnginePluginLibrariesTab := HotspotTab("Libraries", 650, 168)
EnginePluginAddLibraryButton := EnginePluginLibrariesTab.AddHotspotButton("Add library", 652, 204, "FocusedEnginePluginAddLibraryButton")
EnginePluginUserFolderTab := HotspotTab("User folder", 716, 168)
EnginePluginOutputSurrTab := HotspotTab("Output/Surr", 788, 168)
EnginePluginMiscTab := HotspotTab("Misc.", 872, 168)
EnginePluginPreferencesTab.AddTabControl("", EnginePluginEngineTab, EnginePluginLibrariesTab, EnginePluginUserFolderTab, EnginePluginOutputSurrTab, EnginePluginMiscTab)
Plugin.RegisterOverlay("Engine", EnginePluginOverlay)

EngineStandaloneOverlay := AccessibilityOverlay("Engine")
EngineStandaloneOverlay.AddHotspotButton("Load instrument", 112, 180)
EngineStandaloneQuickEditTab := HotspotTab("Quick edit", 352, 72)
EngineStandaloneProEditTab := HotspotTab("Pro edit", 424, 72)
EngineStandaloneBrowserTab := HotspotTab("Browser", 488, 72)
EngineStandaloneMixerTab := HotspotTab("Mixer", 528, 72)
EngineStandalonePreferencesTab := HotspotTab("Preferences", 580, 72)
EngineStandaloneHelpTab := HotspotTab("Help", 600, 72)
EngineStandaloneOverlay.AddTabControl("", EngineStandaloneQuickEditTab, EngineStandaloneProEditTab, EngineStandaloneBrowserTab, EngineStandaloneMixerTab, EngineStandalonePreferencesTab, EngineStandaloneHelpTab)
EngineStandaloneEngineTab := HotspotTab("Engine", 396, 112)
EngineStandaloneLibrariesTab := HotspotTab("Libraries", 424, 112)
EngineStandaloneAddLibraryButton := EngineStandaloneLibrariesTab.AddHotspotButton("Add library", 436, 146)
EngineStandaloneUserFolderTab := HotspotTab("User folder", 488, 112)
EngineStandaloneOutputSurrTab := HotspotTab("Output/Surr", 572, 112)
EngineStandaloneMiscTab := HotspotTab("Misc.", 656, 112)
EngineStandalonePreferencesTab.AddTabControl("", EngineStandaloneEngineTab, EngineStandaloneLibrariesTab, EngineStandaloneUserFolderTab, EngineStandaloneOutputSurrTab, EngineStandaloneMiscTab)
Standalone.RegisterOverlay("Engine", EngineStandaloneOverlay)

NucleusOverlay := AccessibilityOverlay("Nucleus")
NucleusOverlay.AddHotspotButton("Classic Mix", 690, 402)
NucleusOverlay.AddHotspotButton("Modern Mix", 690, 432)
Plugin.RegisterOverlay("Kontakt/Komplete Kontrol", NucleusOverlay)

ShreddageOverlay := AccessibilityOverlay("Shreddage")
ShreddageOverlay.AddHotspotButton("Guitar Number 1", 1052, 524)
ShreddageOverlay.AddHotspotButton("Guitar Number 2", 1076, 524,)
ShreddageOverlay.AddHotspotButton("Guitar Number 3", 1100, 524)
ShreddageOverlay.AddHotspotButton("Guitar Number 4", 1124, 524)
Plugin.RegisterOverlay("Kontakt/Komplete Kontrol", ShreddageOverlay)
