#Requires AutoHotkey v2.0

Plugin.DefaultOverlay := AccessibilityOverlay()
Plugin.DefaultOverlay.AddSpeechOutput("No overlay defined")
Plugin.ChooserOverlay := AccessibilityOverlay()
Plugin.ChooserOverlay.AddCustomButton("Choose overlay",, ChoosePluginOverlay)

Standalone.DefaultOverlay := AccessibilityOverlay()
Standalone.DefaultOverlay.AddSpeechOutput("No overlay defined")
Standalone.ChooserOverlay := AccessibilityOverlay()
Standalone.ChooserOverlay.AddCustomButton("Choose overlay",, ChooseStandaloneOverlay)

AreiaOverlay := AccessibilityOverlay("Areia")
AreiaOverlay.Metadata := Map("Vendor", "Audio Imperia", "Product", "Areia")
AreiaOverlay.AddHotspotButton("Classic Mix", 678, 448)
AreiaOverlay.AddHotspotButton("Modern Mix", 775, 448)
Plugin.RegisterOverlay("Kontakt/Komplete Kontrol", AreiaOverlay)

JaegerOverlay := AccessibilityOverlay("Jaeger")
JaegerOverlay.Metadata := Map("Vendor", "Audio Imperia", "Product", "Jaeger")
JaegerOverlay.AddHotspotButton("Classic Mix", 678, 448)
JaegerOverlay.AddHotspotButton("Modern Mix", 775, 448)
Plugin.RegisterOverlay("Kontakt/Komplete Kontrol", JaegerOverlay)

NucleusOverlay := AccessibilityOverlay("Nucleus")
NucleusOverlay.Metadata := Map("Vendor", "Audio Imperia", "Product", "Nucleus")
NucleusOverlay.AddHotspotButton("Classic Mix", 690, 402)
NucleusOverlay.AddHotspotButton("Modern Mix", 690, 432)
Plugin.RegisterOverlay("Kontakt/Komplete Kontrol", NucleusOverlay)

TalosOverlay := AccessibilityOverlay("Talos")
TalosOverlay.Metadata := Map("Vendor", "Audio Imperia", "Product", "Talos")
TalosOverlay.AddHotspotButton("Classic Mix", 678, 448)
TalosOverlay.AddHotspotButton("Modern Mix", 775, 448)
Plugin.RegisterOverlay("Kontakt/Komplete Kontrol", TalosOverlay)

EnginePluginOverlay := AccessibilityOverlay("Engine")
EnginePluginOverlay.Metadata := Map("Vendor", "Best Service", "Product", "Engine")
EnginePluginOverlay.AddHotspotButton("Load instrument", 320, 232)
EnginePluginQuickEditTab := HotspotTab("Quick edit", 574, 124)
EnginePluginProEditTab := HotspotTab("Pro edit", 628, 124)
EnginePluginBrowserTab := HotspotTab("Browser", 686, 124)
EnginePluginMixerTab := HotspotTab("Mixer", 744, 124)
EnginePluginPreferencesTab := HotspotTab("Preferences", 800, 124)
EnginePluginHelpTab := HotspotTab("Help", 850, 124)
EnginePluginOverlay.AddTabControl(, EnginePluginQuickEditTab, EnginePluginProEditTab, EnginePluginBrowserTab, EnginePluginMixerTab, EnginePluginPreferencesTab, EnginePluginHelpTab)
EnginePluginEngineTab := HotspotTab("Engine", 576, 168)
EnginePluginLibrariesTab := HotspotTab("Libraries", 650, 168)
EnginePluginAddLibraryButton := EnginePluginLibrariesTab.AddHotspotButton("Add library", 652, 204, FocusedEnginePluginAddLibraryButton)
EnginePluginUserFolderTab := HotspotTab("User folder", 716, 168)
EnginePluginOutputSurrTab := HotspotTab("Output/Surr", 788, 168)
EnginePluginMiscTab := HotspotTab("Misc.", 872, 168)
EnginePluginPreferencesTab.AddTabControl(, EnginePluginEngineTab, EnginePluginLibrariesTab, EnginePluginUserFolderTab, EnginePluginOutputSurrTab, EnginePluginMiscTab)
Plugin.RegisterOverlay("Engine", EnginePluginOverlay)

EngineStandaloneOverlay := AccessibilityOverlay("Engine")
EngineStandaloneOverlay.Metadata := Map("Vendor", "Best Service", "Product", "Engine")
EngineStandaloneOverlay.AddHotspotButton("Load instrument", 112, 180)
EngineStandaloneQuickEditTab := HotspotTab("Quick edit", 352, 72)
EngineStandaloneProEditTab := HotspotTab("Pro edit", 424, 72)
EngineStandaloneBrowserTab := HotspotTab("Browser", 488, 72)
EngineStandaloneMixerTab := HotspotTab("Mixer", 528, 72)
EngineStandalonePreferencesTab := HotspotTab("Preferences", 580, 72)
EngineStandaloneHelpTab := HotspotTab("Help", 600, 72)
EngineStandaloneOverlay.AddTabControl(, EngineStandaloneQuickEditTab, EngineStandaloneProEditTab, EngineStandaloneBrowserTab, EngineStandaloneMixerTab, EngineStandalonePreferencesTab, EngineStandaloneHelpTab)
EngineStandaloneEngineTab := HotspotTab("Engine", 396, 112)
EngineStandaloneLibrariesTab := HotspotTab("Libraries", 424, 112)
EngineStandaloneAddLibraryButton := EngineStandaloneLibrariesTab.AddHotspotButton("Add library", 436, 146)
EngineStandaloneUserFolderTab := HotspotTab("User folder", 488, 112)
EngineStandaloneOutputSurrTab := HotspotTab("Output/Surr", 572, 112)
EngineStandaloneMiscTab := HotspotTab("Misc.", 656, 112)
EngineStandalonePreferencesTab.AddTabControl(, EngineStandaloneEngineTab, EngineStandaloneLibrariesTab, EngineStandaloneUserFolderTab, EngineStandaloneOutputSurrTab, EngineStandaloneMiscTab)
Standalone.RegisterOverlay("Engine", EngineStandaloneOverlay)

ShreddageOverlay := AccessibilityOverlay("Shreddage Series")
ShreddageOverlay.Metadata := Map("Vendor", "Impact Soundworks", "Product", "Shreddage Series")
ShreddageOverlay.AddHotspotButton("Guitar Number 1", 1052, 524)
ShreddageOverlay.AddHotspotButton("Guitar Number 2", 1076, 524,)
ShreddageOverlay.AddHotspotButton("Guitar Number 3", 1100, 524)
ShreddageOverlay.AddHotspotButton("Guitar Number 4", 1124, 524)
Plugin.RegisterOverlay("Kontakt/Komplete Kontrol", ShreddageOverlay)
