on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write build number
        uses: DamianReeves/write-file-action@master
        with:
          path: Includes/CIVersion.ahk
          write-mode: overwrite
          contents: |
            BuildNumber := "${{ github.run_id }}"
      - name: Build with AHK v2.0.10
        uses: Timtam/autohotkey-build@master
        with:
          version: v2.0.10
          x64: true
          x86: true
          compression: none
          in: ReaHotkey.ahk
          out: "build"
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1.1.0
        with:
          path: README.md
          outputpath: build
      -
        name: "Prepare artifact"
        run: |
          xcopy Images build\Images /I /S
          xcopy Sounds build\Sounds /I
          xcopy bassasio32.dll build
          xcopy bassasio64.dll build
          xcopy nvdaControllerClient32.dll build
          xcopy nvdaControllerClient64.dll build
      -
        name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "ReaHotkey"
          path: build/
